const PRODUCTS={1:['SGC Cream','SGC Kulit'],2:['Malkist Abon','Malkist Sour Cream','SCO Bakaran'],3:['Coconut','Choki Cream'],4:['Malkist Crackers Murni','MCR Bakaran'],5:['RSC Cream','RSC Kulit (Lokal)','Roma Sandwich Vanilla (Kulit)','Arden']};
const ROOM_NAMES={1:'Ruangan Line 1',2:'Ruangan Line 2',3:'Ruangan Line 3',4:'Ruangan Line 4',5:'Ruangan Line 5'};
const BAG_KG=20, state={};
const linesEl=document.getElementById('lines'),grandTotalEl=document.getElementById('grandTotal'),output=document.getElementById('waOutput'),dateEl=document.getElementById('date'),shiftEl=document.getElementById('shift'),toast=document.getElementById('toast');
dateEl.value=new Date().toISOString().slice(0,10);
const key=(l,n)=>`${l}|${n}`, format=n=>n.toLocaleString('id-ID');
function toastMsg(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function render(){linesEl.innerHTML='';for(let line=1;line<=5;line++){const card=document.createElement('section');card.className='card line-card';card.innerHTML=`<div class="line-title"><h2>Line ${line}</h2><span class="room-label">${ROOM_NAMES[line]}</span></div>`;PRODUCTS[line].forEach(name=>{const k=key(line,name),s=state[k]||0,kg=s*BAG_KG,row=document.createElement('div');row.className='product';row.innerHTML=`<div class="product-top"><div class="product-name">${name}</div><div class="kg" id="kg-${cssId(k)}">${format(kg)} kg</div></div><div class="counter"><button type="button" data-action="minus" data-key="${k}">−</button><input data-key="${k}" type="number" min="0" inputmode="numeric" value="${s}"><button type="button" data-action="plus" data-key="${k}">+</button><span class="unit">kantong</span></div>`;card.appendChild(row)});linesEl.appendChild(card)}attachEvents();updateSummary();generateWA()}
function cssId(s){return s.replace(/[^a-zA-Z0-9]/g,'_')}
function attachEvents(){document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const k=btn.dataset.key;state[k]=btn.dataset.action==='plus'?(state[k]||0)+1:Math.max(0,(state[k]||0)-1);render()}));document.querySelectorAll('input[data-key]').forEach(inp=>inp.addEventListener('input',()=>{state[inp.dataset.key]=Math.max(0,parseInt(inp.value||0,10)||0);document.getElementById(`kg-${cssId(inp.dataset.key)}`).textContent=`${format(state[inp.dataset.key]*BAG_KG)} kg`;updateSummary();generateWA()}))}
function total(){return Object.values(state).reduce((a,b)=>a+b*BAG_KG,0)}
function updateSummary(){grandTotalEl.textContent=`${format(total())} kg`}
function formatDate(v){if(!v)return '';const [y,m,d]=v.split('-');const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];return `${Number(d)} ${months[Number(m)-1]} ${y}`}
function generateWA(){let text=`OPNAME BUBUK DI AREA STAGE 1\nTanggal ${formatDate(dateEl.value)} SHIFT ${shiftEl.value}\n\n`;for(let line=1;line<=5;line++){text+=`Line ${line}\n`;PRODUCTS[line].forEach(name=>{const kg=(state[key(line,name)]||0)*BAG_KG;text+=`${name} : ${kg===0?'-':format(kg)+' kg'}\n`});text+='\n'}text+=`Total : ${format(total())} kg`;output.value=text}
function saveOpname(){const snapshot={date:dateEl.value,shift:shiftEl.value,savedAt:new Date().toISOString(),data:{...state},total:total(),text:output.value};localStorage.setItem('opnameTerakhir',JSON.stringify(snapshot));document.getElementById('savedCard').classList.remove('hidden');document.getElementById('savedInfo').textContent=`${formatDate(snapshot.date)} • Shift ${snapshot.shift} • Total ${format(snapshot.total)} kg`;toastMsg('Opname berhasil disimpan')}
document.getElementById('submitBtn').addEventListener('click',()=>{generateWA();saveOpname();output.scrollIntoView({behavior:'smooth',block:'start'})});
document.getElementById('copyBtn').addEventListener('click',async()=>{generateWA();try{await navigator.clipboard.writeText(output.value);toastMsg('Format WA sudah dicopy')}catch{output.select();document.execCommand('copy');toastMsg('Teks sudah dipilih, tinggal Copy')}});
document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('Reset semua input opname?')){Object.keys(state).forEach(k=>delete state[k]);document.getElementById('savedCard').classList.add('hidden');render();toastMsg('Input direset')}});
document.getElementById('historyBtn').addEventListener('click',()=>{const box=document.getElementById('historyBox');const raw=localStorage.getItem('opnameTerakhir');if(!raw){box.textContent='Belum ada opname tersimpan.'}else{const x=JSON.parse(raw);box.textContent=`Opname terakhir: ${formatDate(x.date)} • Shift ${x.shift} • Total ${format(x.total)} kg`}box.classList.toggle('hidden')});
dateEl.addEventListener('change',generateWA);shiftEl.addEventListener('change',generateWA);render();
